# Site settings
title: Loic Nogues - Web developer
email: nogues.loic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: m0g
github_url: "https://github.com/m0g/"
h1: Loic Nogues
subtitle: Web developer

# Build settings
markdown: kramdown
